name: Quality checks

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.4"
        composer-version:
          - "v1"

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:${{ matrix.composer-version }}

      - uses: ./.github/actions/composer-install

      - name: Run unit tests
        run: make test-unit

      - name: Run mutation tests
        run: make test-mutation

  static-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v1

      - uses: ./.github/actions/composer-install

      - name: Run static analysis
        run: make static-analysis

  style-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v1

      - uses: ./.github/actions/composer-install

      - name: Run style checker
        run: make cs-check
